"""
Django settings for dashboard project.

Generated by 'django-admin startproject' using Django 4.2.25.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import environ

# Initialize environment variables
env = environ.Env(
    DEBUG=(bool, False)
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Read .env file
environ.Env.read_env(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY
SECRET_KEY = env("SECRET_KEY")
DEBUG = env("DEBUG")
ALLOWED_HOSTS = ["localhost", "127.0.0.1"]  # Add production hosts here


# Application definition

INSTALLED_APPS = [
    "jazzmin", 
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',   # for frontend React integration
    'users', 
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dashboard.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dashboard.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Database - MySQL
DATABASES = {
    'default': {
        'ENGINE': 'mysql.connector.django',
        'NAME': env("DB_NAME"),
        'USER': env("DB_USER"),
        'PASSWORD': env("DB_PASSWORD"),
        'HOST': env("DB_HOST"),
        'PORT': env("DB_PORT", default="3306"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'

# For development: where you put your custom static files
STATICFILES_DIRS = [
    BASE_DIR / 'static',  # outer dashboard/static
]

# For production: where collectstatic will gather all static files
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Custom user model
AUTH_USER_MODEL = 'users.Users'

# CORS settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
]

# REST framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# ==========================================
#  JAZZMIN SETTINGS — Admin
# ==========================================

JAZZMIN_SETTINGS = {
    # ----- Branding -----
    "site_logo": "images/logo.png",
    "site_icon": "images/logo.png",
    "site_brand": "My Dashboard",
    "site_title": "My Dashboard Admin",
    "welcome_sign": "Welcome to My Dashboard Admin Portal",

    # ----- Navigation -----
    "show_sidebar": True,
    "navigation_expanded": True,

    # ----- App Icons -----
    "icons": {
        "auth.User": "fas fa-user",
        "users.Users": "fas fa-user-circle",
        # "admin_page.billingData": "fas fa-file-invoice",
        # "admin_page.billingLog": "fas fa-file-alt",
        "users.Role": "fas fa-user-tag",
        "users.SubRole": "fas fa-building",
        # "admin_page.ValueStream": "fas fa-stream",
        # "chargenumberlookup.ChargeNumberInfo": "fas fa-file-invoice-dollar",
        # "chargenumberlookup.PageVisit": "fas fa-chart-line",
    },

    # ----- Top Menu Links -----
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "User Login", "url": "/", "new_window": True},
        {
            "name": "Support",
            "url": "https://intranet.collins/support",
            "new_window": True,
        },
    ],

    # ----- UI Builder -----
    "show_ui_builder": True,
}

# ==========================================
# JAZZMIN UI TWEAKS
# ==========================================

JAZZMIN_UI_TWEAKS = {
    # ----- Text & Size -----
    "navbar_small_text": True,
    "footer_small_text": True,
    "body_small_text": True,
    "brand_small_text": True,

    # ----- Colors & Theme -----
    "brand_colour": False,
    "accent": "accent-primary",
    "navbar": "navbar-white navbar-light",
    "navbar_bg": "navbar-dark bg-primary",
    "footer_bg": "bg-light",
    "theme": "lux",               # Light corporate theme
    "dark_mode_theme": "cyborg",  # Optional dark mode

    # ----- Layout -----
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": True,
    "sidebar_fixed": True,

    # ----- Sidebar -----
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,

    # ----- Buttons -----
    "button_classes": {
        "primary": "btn-outline-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },

    # ----- Visibility -----
    "show_ui_builder": True,
    "show_sidebar_toggle": True,
    "show_topmenu": True,
    "show_footer": True,

    # ----- Actions -----
    "actions_sticky_top": True,
}

